### *Author : A Aditya Bhardwaj*
#### Reg. No. : 22226

### Manipulating Matrix:

## $$MDSC-202(P)$$

## $$Assignment-II$$

In [11]:
x <- matrix(data = 1:8,nrow = 4,ncol = 2,byrow = TRUE )
x

[,1] [,2]
[1,] 1    2   
[2,] 3    4   
[3,] 5    6   
[4,] 7    8

In [12]:
# Transpose of x :
xtx <- t(x) %*% x
xtx

[,1] [,2]
[1,]  84  100 
[2,] 100  120

In [13]:
# Crossproduct
xtx1 <- crossprod(x)
xtx1

[,1] [,2]
[1,]  84  100 
[2,] 100  120

In [14]:
# Arithmetic Operations on Matrix:
4*x

[,1] [,2]
[1,]  4    8  
[2,] 12   16  
[3,] 20   24  
[4,] 28   32

In [15]:
4*x - x

[,1] [,2]
[1,]  3    6  
[2,]  9   12  
[3,] 15   18  
[4,] 21   24

In [16]:
x + 4*x

[,1] [,2]
[1,]  5   10  
[2,] 15   20  
[3,] 25   30  
[4,] 35   40

In [17]:
x + 2*x +3*x -4*x

[,1] [,2]
[1,]  2    4  
[2,]  6    8  
[3,] 10   12  
[4,] 14   16

In [18]:
y <- matrix(data = c(84,100,100,120),nrow=2,ncol = 2,byrow = TRUE)
y

[,1] [,2]
[1,]  84  100 
[2,] 100  120

In [19]:
# Finding Inverse:
solve(y)

[,1]  [,2] 
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [20]:
y%*% solve(y)

[,1] [,2]
[1,] 1    0   
[2,] 0    1

In [21]:
# Eigen Values & Eigen Vectors 
eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230
