## Name: A Aditya Bhardwaj
### Reg.No. : 22226

### <Center> Regression Methods (Lab) Assignment-I

### Basic Arithmetic Operations

In [30]:
a<-2
b<-3

sprintf("Add: %d",a+b)

[1] "Add: 5"

In [31]:
sprintf("sub: %d",a-b)

[1] "sub: -1"

In [32]:
sprintf("mul:- %d",a*b)

[1] "mul:- 6"

In [33]:
sprintf("div:- %f",b/a)

[1] "div:- 1.500000"

In [34]:
sprintf("power:- %d",a^b)

[1] "power:- 8"

In [35]:
sprintf("modulus:- %d",a%%b)

[1] "modulus:- 2"

In [36]:
sprintf("Integer Division:- %d",a%/%b)

[1] "Integer Division:- 0"

### Comparison Operations

In [39]:
a<-1
b<-1
if(a==b){
    print("both variables are equal")
}else{
    print("both variables are not equal")
}

[1] "both variables are equal"


In [40]:
a<-3
b<-4
if(a!=b){
    print("both variables are not equal")
}else{
    print("both variables are equal")
}

[1] "both variables are not equal"


In [43]:
a<-8
if(a>=6){
    print(a)
}

[1] 8


In [46]:
b<-100
if(a<b){
    print("b is greater than a")
}

[1] "b is greater than a"


In [47]:
if(b>=7){
    print(TRUE)
}

[1] TRUE


### Vectors

In [1]:
abd<-c("hello","world")
print(abd)

[1] "hello" "world"


In [4]:
# Concatinating two vectors
xa<-c('hello')
xb<-c('world')
cat(xa,xb)

hello world

In [5]:
# Operations on vectors
#adding corresponding elements in two vectors
a<-c(1,2,3)
b<-c(4,5,6)
c<-a+b
print(c)

[1] 5 7 9


In [6]:
print(class(c)) #shows the data type of the variable

[1] "numeric"


In [7]:
#multiplying corresponding elements in two vectors
a<-c(1,2,3)
b<-c(4,5,6)
c<-a*b
c

[1]  4 10 18

In [8]:
#subtracting corresponding elements in two vectors
a<-c(1,2,3)
b<-c(4,5,6)
c<-a-b
c

[1] -3 -3 -3

In [9]:
#dividing corresponding elements in two vectors
a<-c(1,2,3)
b<-c(4,5,6)
c<-a/b
c

[1] 0.25 0.40 0.50

### Lists

In [10]:
mysub<-list(c(1,2,3,4,5))
print(mysub)

[[1]]
[1] 1 2 3 4 5



In [11]:
print(class(mysub))

[1] "list"


In [12]:
#Appending two lists
a<-list(1,2,3)
b<-list(5,6,7)
z<-append(a,b)
z

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 5

[[5]]
[1] 6

[[6]]
[1] 7

### Matrices

In [16]:
m <- matrix(nrow = 2, ncol = 4)
m

[,1] [,2] [,3] [,4]
[1,] NA   NA   NA   NA  
[2,] NA   NA   NA   NA

In [18]:
m <- matrix(1:8, nrow = 2, ncol = 4)
m

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

### Arrays

In [21]:
#printing array elements
a <- array(c("o","x"),dim=c(1,2))
a

[,1] [,2]
[1,] o    x

### Factors

In [23]:
courses<-c('Regression Methods','Machine Learning','Big Data Annalysis','Data Engineering','Multivariate Statistical Annalysis')
factor_courses<- factor(courses)
factor_courses

[1] Regression Methods                 Machine Learning                  
[3] Big Data Annalysis                 Data Engineering                  
[5] Multivariate Statistical Annalysis
5 Levels: Big Data Annalysis Data Engineering ... Regression Methods

In [24]:
print(class(factor_courses))

[1] "factor"


In [25]:
print(nlevels(factor_courses))

[1] 5


### DataFrames

In [28]:
sports_perf<-data.frame(
    name=c('aditya','kumar','satya','vamsee','hemanth'),
    height_cm=c(170,169,175,169.5,173),
    weight_kg=c(75,89,66,89,77),
    age_yrs=c(22,21,22,21,22),
    hund_mtr_sec=c(12,9,10,14,13),
    four_hundr_sec=c(40,37,42,39,36)
)
sports_perf

name    height_cm weight_kg age_yrs hund_mtr_sec four_hundr_sec
1 aditya  170.0     75        22      12           40            
2 kumar   169.0     89        21       9           37            
3 satya   175.0     66        22      10           42            
4 vamsee  169.5     89        21      14           39            
5 hemanth 173.0     77        22      13           36