## Name: A Aditya Bhardwaj
### Reg. No : 22226

### <center> MDSC-202(Lab)-Assignment-I

In [3]:
# Matrix Structure
A <- matrix(data=c(5,3,5,2,8,1),nrow=2,ncol=2+1)
A

[,1] [,2] [,3]
[1,] 5    5    8   
[2,] 3    2    1

In [4]:
# Arrangement by Row
B <- matrix(data=c(0,8,5,2,56,41,13,12),nrow=2,ncol=4,byrow=TRUE)
B

[,1] [,2] [,3] [,4]
[1,]  0    8    5    2  
[2,] 56   41   13   12

In [5]:
# Arrangement by Column
B <- matrix(data=c(0,8,5,2,56,41,13,12),nrow=3,ncol=2,byrow=FALSE)
B

Warning message in matrix(data = c(0, 8, 5, 2, 56, 41, 13, 12), nrow = 3, ncol = 2, :
"data length [8] is not a sub-multiple or multiple of the number of rows [3]"


[,1] [,2]
[1,] 0     2  
[2,] 8    56  
[3,] 5    41

In [6]:
# rbind and cbind
rb <- rbind(-13:31,-14:10)
rb

Warning message in rbind(-13:31, -14:10):
"number of columns of result is not a multiple of vector length (arg 2)"


[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13] [,14]
[1,] -13  -12  -11  -10   -9  -8   -7   -6   -5   -4    ⋯     22    23    24   
[2,] -14  -13  -12  -11  -10  -9   -8   -7   -6   -5    ⋯     -4    -3    -2   
     [,15] [,16] [,17] [,18] [,19] [,20] [,21]
[1,] 25    26    27    28    29    30    31   
[2,] -1     0     1     2     3     4     5

In [7]:
cb<- cbind(-21:12,-12:21)
cb

[,1] [,2]
 [1,] -21  -12 
 [2,] -20  -11 
 [3,] -19  -10 
 [4,] -18   -9 
 [5,] -17   -8 
 [6,] -16   -7 
 [7,] -15   -6 
 [8,] -14   -5 
 [9,] -13   -4 
[10,] -12   -3 
[11,] -11   -2 
[12,] -10   -1 
[13,]  -9    0 
[14,]  -8    1 
[15,]  -7    2 
[16,]  -6    3 
[17,]  -5    4 
[18,]  -4    5 
[19,]  -3    6 
[20,]  -2    7 
[21,]  -1    8 
[22,]   0    9 
[23,]   1   10 
[24,]   2   11 
[25,]   3   12 
[26,]   4   13 
[27,]   5   14 
[28,]   6   15 
[29,]   7   16 
[30,]   8   17 
[31,]   9   18 
[32,]  10   19 
[33,]  11   20 
[34,]  12   21

In [8]:
A <-matrix(data=c(12,12,33,41,35,56),nrow=2,ncol=3)
A

[,1] [,2] [,3]
[1,] 12   33   35  
[2,] 12   41   56

In [9]:
# Dimension
dim(A)

[1] 2 3

In [10]:
dim(A)[2]

[1] 3

In [11]:
# No of rows
nrow(A)

[1] 2

In [12]:
# No of columns
ncol(A)

[1] 3

In [14]:
# Extracting elements from a Matrix

A <- matrix(c(.16,.22,7.3,.49,6.5,8.61,1.7,3.8,5.9,13,31.1,61.2,91.3,21.42,21.53,21.63),nrow=4,ncol=4)
A

[,1] [,2] [,3] [,4] 
[1,] 0.16 6.50  5.9 91.30
[2,] 0.22 8.61 13.0 21.42
[3,] 7.30 1.70 31.1 21.53
[4,] 0.49 3.80 61.2 21.63

In [15]:
# 1.Diagonal elements of a Matrix
diag(x=A)   

[1]  0.16  8.61 31.10 21.63

In [16]:
# 2. Element of 3rd row and 2nd column
A[3,2]

[1] 1.7

In [17]:
# 3. Elements of 2nd column
A[,2]

[1] 6.50 8.61 1.70 3.80

In [18]:
# 4. Extracting 2nd and 3rd rows
A[2:3,]

[,1] [,2] [,3] [,4] 
[1,] 0.22 8.61 13.0 21.42
[2,] 7.30 1.70 31.1 21.53

In [19]:
# 5. Extracting 4th and 2nd column
A[,c(4,2)]

[,1]  [,2]
[1,] 91.30 6.50
[2,] 21.42 8.61
[3,] 21.53 1.70
[4,] 21.63 3.80

In [20]:
# 6. Extracting (4,2) ,(4,3) , (3,2) and (3,3) values
A[c(4,3),2:3]

[,1] [,2]
[1,] 3.8  61.2
[2,] 1.7  31.1

### Manipulating a Matrix

In [22]:
A <- matrix(c(.16,.22,7.3,.49,6.5,8.61,1.7,3.8,5.9,13,31.1,61.2,91.3,21.42,21.53,21.63),nrow=4,ncol=4)
A

[,1] [,2] [,3] [,4] 
[1,] 0.16 6.50  5.9 91.30
[2,] 0.22 8.61 13.0 21.42
[3,] 7.30 1.70 31.1 21.53
[4,] 0.49 3.80 61.2 21.63

In [23]:
# Removing column 2 from the matrix
A[,-2]

[,1] [,2] [,3] 
[1,] 0.16  5.9 91.30
[2,] 0.22 13.0 21.42
[3,] 7.30 31.1 21.53
[4,] 0.49 61.2 21.63

In [24]:
# Removing row 4 and selecting column 3,2 and 1 in this order
A[-4,3:1]

[,1] [,2] [,3]
[1,]  5.9 6.50 0.16
[2,] 13.0 8.61 0.22
[3,] 31.1 1.70 7.30

In [25]:
# Removing row 2 and column 3
A[-2,-3]

[,1] [,2] [,3] 
[1,] 0.16 6.5  91.30
[2,] 7.30 1.7  21.53
[3,] 0.49 3.8  21.63

In [26]:
# Removing row 2 and columns 3 and 4
A[-2,-c(3,4)]

[,1] [,2]
[1,] 0.16 6.5 
[2,] 7.30 1.7 
[3,] 0.49 3.8

In [27]:
# Copying A into B
B<-A
B

[,1] [,2] [,3] [,4] 
[1,] 0.16 6.50  5.9 91.30
[2,] 0.22 8.61 13.0 21.42
[3,] 7.30 1.70 31.1 21.53
[4,] 0.49 3.80 61.2 21.63

In [28]:
# Replacing 3rd row of B with integers 1,2,3 and 4
B[3,]<- 1:4
B

[,1] [,2] [,3] [,4] 
[1,] 0.16 6.50  5.9 91.30
[2,] 0.22 8.61 13.0 21.42
[3,] 1.00 2.00  3.0  4.00
[4,] 0.49 3.80 61.2 21.63

In [29]:
# Replacing elements in (row 3,column 3) and (row 4,column 3) with value 100
B[c(3,4),3]<-100
B

[,1] [,2] [,3]  [,4] 
[1,] 0.16 6.50   5.9 91.30
[2,] 0.22 8.61  13.0 21.42
[3,] 1.00 2.00 100.0  4.00
[4,] 0.49 3.80 100.0 21.63

In [30]:
# Replacing a Matrix's row with its column
# Before changing
B

[,1] [,2] [,3]  [,4] 
[1,] 0.16 6.50   5.9 91.30
[2,] 0.22 8.61  13.0 21.42
[3,] 1.00 2.00 100.0  4.00
[4,] 0.49 3.80 100.0 21.63

In [31]:
# After changing
B<-A
B[4,]<-B[,4]
B

[,1]  [,2]  [,3]  [,4] 
[1,]  0.16  6.50  5.90 91.30
[2,]  0.22  8.61 13.00 21.42
[3,]  7.30  1.70 31.10 21.53
[4,] 91.30 21.42 21.53 21.63

In [32]:
# Changing matrix elements with vector
B[c(1,4),2:1]<-c(-100,100,-600,600)
B

[,1]    [,2]    [,3]  [,4] 
[1,] -600.00 -100.00  5.90 91.30
[2,]    0.22    8.61 13.00 21.42
[3,]    7.30    1.70 31.10 21.53
[4,]  600.00  100.00 21.53 21.63

In [33]:
B[c(1,4),c(1,4)]<-c(-20,20)
B

[,1]   [,2]    [,3]  [,4]  
[1,] -20.00 -100.00  5.90 -20.00
[2,]   0.22    8.61 13.00  21.42
[3,]   7.30    1.70 31.10  21.53
[4,]  20.00  100.00 21.53  20.00

In [34]:
# Filling Diagonal elements of B with -99

diag(B)<-rep(x=-99,times=4)
B

[,1]   [,2]   [,3]   [,4]  
[1,] -99.00 -100.0   5.90 -20.00
[2,]   0.22  -99.0  13.00  21.42
[3,]   7.30    1.7 -99.00  21.53
[4,]  20.00  100.0  21.53 -99.00